apiVersion: v1
kind: Service

metadata:
  name: db-service
  namespace: default

spec:
  ports:
  - port: 80
    targetPort: 27017

  selector:
    app: node # connect this service to deployment

  type: LoadBalancer # also use LoadBalancer - for local use cluster IP