apiVersion: v1
kind: Service

metadata:
  name: nginx-service
  namespace: default

spec:
  ports:
  - nodePort: 30001 # range is 30000-32768
    port: 80
    targetPort: 80

  selector:
    app: nginx # connect this service to deployment

  type: NodePort # also use LoadBalancer - for local use cluster IP