apiVersion: v1
kind: Service

metadata:
  name: node-service
  namespace: default

spec:
  ports:
  - port: 80
    targetPort: 3000

  selector:
    app: node # connect this service to deployment

  type: LoadBalancer # also use LoadBalancer - for local use cluster IP