# services: 
#   db:
#     image: mongo
#     ports:
#       - "27017:27017"

#   app:
#     restart: always
#     build: ./nodeapp/app
#     ports:
#       - "3000:3000"
#     links:
#       - db
#     environment: 
#       - DB_HOST=mongodb://mongo:27017/posts
#     depends_on:
#       - db
services:
  db:
    image: mongo-express
    ports:
      - "27017:27017"

  app:
    build: ./app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=mongodb://localhost:27017/posts
    command: "node seeds/seed.js"
    depends_on:
      - db

